services:
  mysql:
    image: mysql:8.0
    container_name: fastapi-demo-mysql
    restart: unless-stopped
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: fastapi-demo
    volumes:
      - py_demo_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot123"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2
    container_name: fastapi-demo-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - py_demo_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  py_demo_mysql_data:
  py_demo_redis_data:
